defaults:
  - default

strategy:
  _target_: lightning.pytorch.strategies.DDPStrategy
  static_graph: True
  gradient_as_bucket_view: True

accelerator: gpu
devices: 2
num_nodes: 1
sync_batchnorm: False
