defaults:
  - ema
  - model_checkpoint
  - _self_

model_checkpoint:
  dirpath: ${paths.output_dir}/checkpoints
  filename: "ldm-latent_ae-epoch@{epoch}-step@{step}-val_loss@{val/loss:.4f}"
  monitor: "val/loss"
  mode: "min"
  save_last: True
